<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ScenarioTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('scenario')->insert([
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 5,
                'place'               => 1,
                'daytime'             => 'morning',
                'char_id'             => 1,
                'title'               => '学校のぷーる',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 5,
                'place'               => 2,
                'daytime'             => 'noon',
                'char_id'             => 1,
                'title'               => '学校の教室',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 5,
                'place'               => 3,
                'daytime'             => 'night',
                'char_id'             => 1,
                'title'               => '学校の保健室',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 1,
                'place'               => 1,
                'daytime'             => 'morning',
                'char_id'             => 2,
                'title'               => '華姫寮の部屋',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 1,
                'place'               => 2,
                'daytime'             => 'noon',
                'char_id'             => 2,
                'title'               => '華姫寮のトイレ',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 1,
                'place'               => 3,
                'daytime'             => 'night',
                'char_id'             => 2,
                'title'               => '華姫寮のお風呂',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 4,
                'place'               => 1,
                'daytime'             => 'morning',
                'char_id'             => 3,
                'title'               => '繁華街のゲームセンター',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 4,
                'place'               => 2,
                'daytime'             => 'noon',
                'char_id'             => 3,
                'title'               => '繁華街のレストラン',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 4,
                'place'               => 3,
                'daytime'             => 'night',
                'char_id'             => 3,
                'title'               => '繁華街の映画館',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 3,
                'place'               => 1,
                'daytime'             => 'morning',
                'char_id'             => 4,
                'title'               => '出身地の駅',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 3,
                'place'               => 2,
                'daytime'             => 'noon',
                'char_id'             => 4,
                'title'               => '出身地の実家',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 3,
                'place'               => 1,
                'daytime'             => 'night',
                'char_id'             => 4,
                'title'               => '出身地の海辺',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 5,
                'place'               => 2,
                'daytime'             => 'morning',
                'char_id'             => 5,
                'title'               => '学校の保健室',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 5,
                'place'               => 3,
                'daytime'             => 'noon',
                'char_id'             => 5,
                'title'               => '学校のプール',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 5,
                'place'               => 1,
                'daytime'             => 'night',
                'char_id'             => 5,
                'title'               => '学校の教室',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 1,
                'place'               => 2,
                'daytime'             => 'morning',
                'char_id'             => 6,
                'title'               => '華姫寮のトイレ',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 1,
                'place'               => 3,
                'daytime'             => 'noon',
                'char_id'             => 6,
                'title'               => '華姫寮の風呂',
                'default_background'  => 12,
            ],
            [
                'start_datetime'      => '2020-07-20 10:00:00',
                'end_datetime'        => '2020-09-20 23:59:59’',
                'field'               => 1,
                'place'               => 1,
                'daytime'             => 'night',
                'char_id'             => 6,
                'title'               => '華姫寮の部屋',
                'default_background'  => 12,
            ],
        ]);
    }
}
