<?php

use Illuminate\Database\Seeder;

class StudyPointRewardTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('study_point_reward')->insert([
            [
                'char_id'             => 1,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 5,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 1,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 10,
                'item_id'             => 6,
                'category'            => 'avatar_hair',
                'num'                 => 1,
            ],
            [
                'char_id'             => 1,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 15,
                'item_id'             => 9,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 1,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 20,
                'item_id'             => 10,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 1,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 25,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 1,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 30,
                'item_id'             => 16,
                'category'            => 'scene_ero',
                'num'                 => 1,
            ],
            [
                'char_id'             => 1,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 5,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 1,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 10,
                'item_id'             => 6,
                'category'            => 'avatar_hair',
                'num'                 => 1,
            ],
            [
                'char_id'             => 1,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 15,
                'item_id'             => 9,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 1,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 20,
                'item_id'             => 10,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 1,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 25,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 1,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 30,
                'item_id'             => 22,
                'category'            => 'scene_ero',
                'num'                 => 1,
            ],
            [
                'char_id'             => 2,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 5,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 2,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 10,
                'item_id'             => 6,
                'category'            => 'avatar_hair',
                'num'                 => 1,
            ],
            [
                'char_id'             => 2,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 15,
                'item_id'             => 9,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 2,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 20,
                'item_id'             => 10,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 2,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 25,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 2,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 30,
                'item_id'             => 17,
                'category'            => 'scene_ero',
                'num'                 => 1,
            ],
            [
                'char_id'             => 2,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 5,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 2,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 10,
                'item_id'             => 6,
                'category'            => 'avatar_hair',
                'num'                 => 1,
            ],
            [
                'char_id'             => 2,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 15,
                'item_id'             => 9,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 2,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 20,
                'item_id'             => 10,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 2,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 25,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 2,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 30,
                'item_id'             => 23,
                'category'            => 'scene_ero',
                'num'                 => 1,
            ],
            [
                'char_id'             => 3,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 5,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 3,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 10,
                'item_id'             => 6,
                'category'            => 'avatar_hair',
                'num'                 => 1,
            ],
            [
                'char_id'             => 3,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 15,
                'item_id'             => 9,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 3,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 20,
                'item_id'             => 10,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 3,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 25,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 3,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 30,
                'item_id'             => 18,
                'category'            => 'scene_ero',
                'num'                 => 1,
            ],
            [
                'char_id'             => 3,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 5,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 3,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 10,
                'item_id'             => 6,
                'category'            => 'avatar_hair',
                'num'                 => 1,
            ],
            [
                'char_id'             => 3,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 15,
                'item_id'             => 9,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 3,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 20,
                'item_id'             => 10,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 3,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 25,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 3,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 30,
                'item_id'             => 24,
                'category'            => 'scene_ero',
                'num'                 => 1,
            ],
            [
                'char_id'             => 4,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 5,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 4,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 10,
                'item_id'             => 6,
                'category'            => 'avatar_hair',
                'num'                 => 1,
            ],
            [
                'char_id'             => 4,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 15,
                'item_id'             => 9,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 4,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 20,
                'item_id'             => 10,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 4,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 25,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 4,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 30,
                'item_id'             => 19,
                'category'            => 'scene_ero',
                'num'                 => 1,
            ],
            [
                'char_id'             => 4,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 5,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 4,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 10,
                'item_id'             => 6,
                'category'            => 'avatar_hair',
                'num'                 => 1,
            ],
            [
                'char_id'             => 4,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 15,
                'item_id'             => 9,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 4,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 20,
                'item_id'             => 10,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 4,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 25,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 4,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 30,
                'item_id'             => 25,
                'category'            => 'scene_ero',
                'num'                 => 1,
            ],
            [
                'char_id'             => 5,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 5,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 5,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 10,
                'item_id'             => 6,
                'category'            => 'avatar_hair',
                'num'                 => 1,
            ],
            [
                'char_id'             => 5,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 15,
                'item_id'             => 9,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 5,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 20,
                'item_id'             => 10,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 5,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 25,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 5,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 30,
                'item_id'             => 20,
                'category'            => 'scene_ero',
                'num'                 => 1,
            ],
            [
                'char_id'             => 5,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 5,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 5,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 10,
                'item_id'             => 6,
                'category'            => 'avatar_hair',
                'num'                 => 1,
            ],
            [
                'char_id'             => 5,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 15,
                'item_id'             => 9,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 5,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 20,
                'item_id'             => 10,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 5,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 25,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 5,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 30,
                'item_id'             => 26,
                'category'            => 'scene_ero',
                'num'                 => 1,
            ],
            [
                'char_id'             => 6,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 5,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 6,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 10,
                'item_id'             => 6,
                'category'            => 'avatar_hair',
                'num'                 => 1,
            ],
            [
                'char_id'             => 6,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 15,
                'item_id'             => 9,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 6,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 20,
                'item_id'             => 10,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 6,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 25,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 6,
                'attitude'            => 'dere',
                'term_id'             => 1,
                'need_score'          => 30,
                'item_id'             => 21,
                'category'            => 'scene_ero',
                'num'                 => 1,
            ],
            [
                'char_id'             => 6,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 5,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 6,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 10,
                'item_id'             => 6,
                'category'            => 'avatar_hair',
                'num'                 => 1,
            ],
            [
                'char_id'             => 6,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 15,
                'item_id'             => 9,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 6,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 20,
                'item_id'             => 10,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 6,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 25,
                'item_id'             => 3,
                'category'            => 'avatar_form',
                'num'                 => 1,
            ],
            [
                'char_id'             => 6,
                'attitude'            => 'tsun',
                'term_id'             => 1,
                'need_score'          => 30,
                'item_id'             => 27,
                'category'            => 'scene_ero',
                'num'                 => 1,
            ],
        ]);
    }
}
